events {}

http {
    server {
        listen 8080;

        location / {
            proxy_pass http://api:3000;
        }

        location /redis/ {
            rewrite ^/redis(/.*)$ $1 break;
            proxy_pass http://redis:4000;
        }
    }
}
